# Eureka - disabled
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT production
spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# gRPC server
spring.grpc.server.port=1010
spring.grpc.server.servlet.enabled=false
asset.service.url=${ASSET_SERVICE_URL:http://localhost:8084}
maintenance.service.url=${MAINTENANCE_SERVICE_URL:http://localhost:8086}
issue.service.url=${ISSUE_SERVICE_URL:http://localhost:8092}

spring.jpa.show-sql=false
